services:
  - type: web
    name: sla-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: sla-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
